name: wott-agent
version: '0.1.2'
summary: Web of Trusted Things agent.
description: |
  tl;dr - WoTT Agent is the Let's Encrypt for IoT.

grade: stable
confinement: strict

apps:
  wott-agent-daemon:
    command: wott-agent
    daemon: oneshot
    plugs:
      - network
    passthrough:
      timer: 00:00-24:00/24

  wott-agent:
    command: wott-agent
    plugs:
      - network

parts:
  wott-agent:
    plugin: python
    python-version: python3
    source: https://github.com/WoTTsecurity/agent.git
    requirements: requirements.txt
    source-type: git
    source-commit: b176349c45338f3adde3fde2c43e260639684033
    build-packages:
      - libssl-dev
      - libffi-dev
      - libffi6
      - libltdl-dev
