name: wott-agent
version: '0.1.13.9'
summary: Web of Trusted Things agent.
description: |
  tl;dr - WoTT Agent is the Let's Encrypt for IoT.
base: core18
grade: stable
confinement: strict
architectures:
  - armhf
  - arm64
  - amd64
  - i386

apps:
  daemon:
    command: wott-agent
    daemon: oneshot
    plugs:
      - firewall-control
      - hardware-observe
      - network
      - network-observe
      - tpm
    passthrough:
      timer: 00:00-24:00/24
    environment:
      XTABLES_LIBDIR: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/xtables

  wott-agent:
    command: wott-agent
    plugs:
      - network
      - network-observe
    environment:
      XTABLES_LIBDIR: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/xtables

  ghostunnel:
    command: ghostunnel
    plugs:
      - network
      - network-bind

  server:
    command: server.sh
    plugs:
      - network
      - network-bind

  client:
    command: client.sh
    plugs:
      - network
      - network-bind

  nmap:
    command: bin/nmap
    plugs:
      - network
      - network-bind
      - network-control

  whoami:
    command: python3 -c 'import agent; print(agent.get_device_id())'

  verify-cert:
    command: openssl verify -CAfile "$SNAP_DATA/ca.crt" "$SNAP_DATA/client.crt"

  inspect-cert:
    command: openssl x509 -in "$SNAP_DATA/client.crt" -text -noout

  test-cert:
    command: python3 -c 'import agent; print(agent.say_hello())'

  portscan:
    command: python3 -c 'import agent; print(agent.get_open_ports())'
    environment:
      XTABLES_LIBDIR: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/xtables

slots:
  wott-certs:
    content: wott-certs
    interface: content
    read:
      - $SNAP_DATA

parts:
  wott-agent:
    plugin: python
    python-version: python3
    source: https://github.com/WoTTsecurity/agent.git
    requirements:
    - requirements.txt
    source-type: git
    source-commit: 7b399029c8da911bd1ef46aabe1079ce815f71b4
    build-packages:
      - libffi-dev
      - libffi6
      - libssl-dev
    stage-packages:
      - libxtables12
      - iptables

  ghostunnel:
    plugin: go
    source: https://github.com/square/ghostunnel.git
    source-tag: v1.3.0
    go-importpath: github.com/square/ghostunnel
    build-packages:
      - build-essential
    stage-packages:
      - libltdl-dev

  tools:
    source: bin/
    plugin: dump
    organize:
        '*': bin/
