name: wott-agent
version: '0.1.10'
summary: Web of Trusted Things agent.
description: |
  tl;dr - WoTT Agent is the Let's Encrypt for IoT.

grade: stable
confinement: strict

apps:
  daemon:
    command: wott-agent
    daemon: oneshot
    plugs:
      - network
      - network-observe
      - hardware-observe
      - tpm
    passthrough:
      timer: 00:00-24:00/24

  wott-agent:
    command: wott-agent
    plugs:
      - network
      - network-observe

  ghostunnel:
    command: ghostunnel
    plugs:
      - network
      - network-bind

  server:
    command: server.sh
    plugs:
      - network
      - network-bind

  client:
    command: client.sh
    plugs:
      - network
      - network-bind

  whoami:
    command: python3 -c 'import agent; print(agent.get_device_id())'

  verify-cert:
    command: openssl verify -CAfile "$SNAP_DATA/ca.crt" "$SNAP_DATA/client.crt"

  inspect-cert:
    command: openssl x509 -in "$SNAP_DATA/client.crt" -text -noout

  test-cert:
    command: python3 -c 'import agent; print(agent.say_hello())'

slots:
  wott-certs:
    content: wott-certs
    interface: content
    read:
      - $SNAP_DATA

parts:
  wott-agent:
    plugin: python
    python-version: python3
    source: https://github.com/WoTTsecurity/agent.git
    requirements: requirements.txt
    source-type: git
    source-commit: 8f97c9bcd6a329e945d88f2127ea96b96a85660f
    build-packages:
      - libssl-dev
      - libffi-dev
      - libffi6

  ghostunnel:
    after: [go]
    source: https://github.com/square/ghostunnel.git
    source-tag: v1.3.0
    source-type: git
    plugin: dump
    build-packages:
      - make
      - libltdl-dev
    override-build: |
      set -xe
      export GOPATH="$(dirname $(pwd))"/go
      mkdir -p $GOPATH $GOPATH/src/github.com/square
      ln -s "$(dirname $(pwd))"/src $GOPATH/src/github.com/square/ghostunnel
      cd $GOPATH/src/github.com/square/ghostunnel && make
      mkdir $SNAPCRAFT_PART_INSTALL/bin
      cp $GOPATH/src/github.com/square/ghostunnel/ghostunnel $SNAPCRAFT_PART_INSTALL/bin/

  tools:
    source: bin/
    plugin: dump
    organize:
        '*': bin/

  go:
    source-tag: go1.11
    source-depth: 1
